services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    whatwedo\SearchBundle\:
        resource: '../../*'

    whatwedo\SearchBundle\Populator\PopulatorInterface:
        class: whatwedo\SearchBundle\Populator\StandardPopulator

    whatwedo\SearchBundle\EventListener\IndexListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
