services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    araise\SearchBundle\:
        resource: '../../*'

    araise\SearchBundle\Populator\PopulatorInterface:
        class: araise\SearchBundle\Populator\OneFieldPopulator

    araise\SearchBundle\EventListener\IndexListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    araise\SearchBundle\Repository\IndexRepository:
        arguments: [ "%araise_search.asterisk_search_enabled%" ]

