name: searchBundle

on:
    push:
        branches: [ 3.0-dev ]
    pull_request:
        branches: [ 3.0-dev ]

jobs:
    phpunit:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
        steps:
            - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
              with:
                  php-version: '8.1'
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            - name: Execute tests (Unit and Feature tests) via PHPUnit
              run: vendor/bin/simple-phpunit
            - name: Check Code Styles
              run: vendor/bin/ecs
            - name: Check PHP Stan
              run: vendor/bin/phpstan analyse src tests
